### ISSUE TITLE
[Bug]: Error 400

### ISSUE THREAD

**Issue by PrzemekSkw** [nurikk/z2m-frontend#1171]
### What happened?

I see that screen when try toopen frontend:
![Zrzut ekranu z 2021-12-14 09-57-49](https://user-images.githubusercontent.com/25219988/145966713-bec8c246-f0ab-40d5-8693-045f71a5dd45.png)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant stacktrace

```shell
I have zigbee2mqtt installed with docker-compose in MiniPC where I have HA-Core. I add to my configuration.yaml in `/homeassistant` folder that line:

frontend:
  port: 8084
```
Regards,
Przemek
```


### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by Gooman-rus** [comment]
Are you trying to access frontend via `http://<ip address>:8084`?
Do you use zigbee2mqtt as a standalone docker container? Maybe you need to forward port 8084 in the zigbee2mqtt docker container configuration?

**Comment by PrzemekSkw** [comment]
I try in local home network.

**Comment by Gooman-rus** [comment]
You need to answer my questions:

1. Are you trying to access frontend via  `http://<ip address>:8084`?
2. Do you use zigbee2mqtt as a standalone docker container? Did you try to forward port 8084 to the main host network in the zigbee2mqtt docker container configuration?

**Comment by PrzemekSkw** [comment]
1. I access http://192.168.0.19:8084 (that is IP of my MiniPC where I have HA installed with zigbee2mqtt)
2. I install zigbee2mqtt with docker-compose. I don't forward port 8084.
My docker-compose file:
```
version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```

**Comment by Gooman-rus** [comment]
You need add this to the `ports` option of the `zigbee2mqtt` container in the docker-compose file:
`- 8084:8084`

**Comment by PrzemekSkw** [comment]
I  add like this:
```
zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
      - 8087:8087
```
I choose port 8087 because there was conflict.
But now I see that empty page: `ERR_EMPTY_RESPONSE`
