### ISSUE TITLE
[Feature request]: (Virtual) Groups of Groups

### ISSUE THREAD

**Issue by PaulMcMillan** [nurikk/z2m-frontend#1433]
(this is a migration of [zigbee2mqtt#12131](https://github.com/Koenkk/zigbee2mqtt/issues/12131) since we agreed it is more appropriate as a frontend feature request)

### Is your feature request related to a problem? Please describe

I have several hundred devices. Many of them represent logical groups (e.g. "Bulb A, B, C in a lamp fixture" - I usually want to control the whole fixture at once). However, I also want to control larger logical partitions (e.g. "All lamps in Room A", or "All the devices in my network"). These larger groups logically exist as a group of groups, but to manage them today, I have to add each individual lamp to every different group it participates in. If I swap a bulb in a fixture, I may have to adjust several different groups to fix things back up. Most of my devices are in at least 4 groups simultaneously.

### Describe the solution you'd like

I want to be able to include an existing group as an element of another group. I know Zigbee doesn't support this directly, but Z2M could keep track of "groups within groups" and flatten/dedupe before sending out changes.

A few complexities:
* Updating a group requires a separate "and update any groups which include this group" call
* We need to gracefully handle recursion (total number of groups is small, so just track and skip already visited groups)

### Describe alternatives you've considered

This can be managed manually, but it encourages subtle errors which aren't immediately obvious.

Another option [raised in the other thread](https://github.com/Koenkk/zigbee2mqtt/issues/12131#issuecomment-1094226510) is "why not send zigbee commands to several groups when you want to make a bigger change." This isn't great for a couple reasons:
* When changing many groups (imagine 50 at once) you clog up your zigbee network with group commands
* It adds latency
* You get the popcorn effect, negating why you used groups in the first place!

### Additional context

Right now if I add, remove, or replace a device, I need to update as many as half a dozen groups individually. With this feature, I could adjust the single most logical grouping, and depend on all others to catch up.

An example of a deeply nested logical group that ends up maintained in many individual groups today:
* Lightbulb A is a member of the Dining Room Chandelier group
* Dining Room Chandelier is a member of Dining Room
* Dining Room is a member of Downstairs
* Downstairs is a member of Inside (in contrast to the Exterior and Pool groups)
* Inside is a member of the Everything group (used for whole-property scenes and bulk turnoff/on)

Today, If I replace Lightbulb A, I have to update each of these groups individually by hand to add the new bulb, and if I miss a layer of logical grouping, I might not notice until those automations leave a single bulb in the wrong state. If we add this feature, I can update the Dining Room Chandelier group and be confident that all groupings down the chain will be properly updated.

**Comment by deviantintegral** [comment]
Hey bot, this would be a great feature to add.

**Comment by PaulMcMillan** [comment]
still not stale

**Comment by EmJay276** [comment]
I would still love to have this feature!

**Comment by EmJay276** [comment]
@PaulMcMillan @deviantintegral 
Using the yaml config and friendly names, it is working fine for me to nest groups into a group.
In the UI they are listed as individual devices in the nested group, but I am fine with that.
I normally only change devices in the lowest level auf groups.

```
groups:
  '8':
    friendly_name: Deckenlicht Wohnzimmer Sofa
    transition: 1
    devices:
      - 0xa4c138be5b86a398/11
  '9':
    friendly_name: Deckenlicht Wohnzimmer Tisch
    transition: 1
    devices:
      - 0x001788010b7fb70b/11
      - 0x001788010b7fa675/11
      - 0x001788010b7f8b7d/11
      - 0x001788010b7f9a5b/11
  '10':
    friendly_name: Deckenlicht Wohnzimmer
    transition: 1
    devices:
      - 'Deckenlicht Wohnzimmer Sofa'
      - 'Deckenlicht Wohnzimmer Tisch'
```
