### ISSUE TITLE
Zigbee2MQTT cannot start

### ISSUE THREAD

**Issue by K0NYC** [nurikk/z2m-frontend#1663]
### What happened?

The add-on fails to start. I'm getting the same results with both Zigbee2MQTT  and Zigbee2MQTT Edge. Enabling/disabling SONOFF Zigbee integration has no effect on the errors. The SONOFF Zigbee dongle works fine because I can connect an Aqara contact sensor to it.

Hardware: `Raspberri Pi 3 (pri3-64)`
HA Platform: `Home Assistant Operating System`
MQTT Broker: `Mosquitto broker add-on (running)`
Adapter: `SONOFF Zigbee 3.0 USB Dongle Plus V2`
Dongle device: ```/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20221031182937-if00` -> ../../ttyACM0```

With serial configured as 
`port: /dev/ttyACM0`
or
`port: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20221031182937-if00`
the error is 
```[09:41:48] INFO: Preparing to start...
[09:41:52] INFO: Socat not enabled
[09:42:03] INFO: Starting Zigbee2MQTT...
TypeError: Cannot create property 'port' on string '/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20221031182937-if00'
    at /app/lib/util/settings.ts:412:45
    at Array.forEach (<anonymous>)
    at iterate (/app/lib/util/settings.ts:384:26)
    at /app/lib/util/settings.ts:423:21
    at Array.forEach (<anonymous>)
    at iterate (/app/lib/util/settings.ts:384:26)
    at /app/lib/util/settings.ts:423:21
    at Array.forEach (<anonymous>)
    at iterate (/app/lib/util/settings.ts:384:26)
    at applyEnvironmentVariables (/app/lib/util/settings.ts:428:5)
```

Setting `port: null` ([autodetect](https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html#:~:text=To%20autodetect%20the%20port%2C%20set%20%27port%3A%20null%27.)) doesn't work. Getting error: 
`Failed to save add-on configuration, Missing required option 'port' in Zigbee2MQTT (45df7312_zigbee2mqtt).`

I verified that the device is owned by `root` and has `777` permissions:

```
$ test -w /dev/ttyACM0 && echo success || echo failure
success
```

Full add-on config:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial:
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20221031182937-if00
zigbee_herdsman_debug: true
```
    
Please help. Thank you.

### What browsers are you seeing the problem on?

Chrome

### Did you download state.json.zip?

no

**Comment by K0NYC** [comment]
**Update:**

I'm [reading](https://www.zigbee2mqtt.io/guide/adapters/#experimental) that the support of the adapters with `EFR32MG21` chip  is in beta stage and it is recommended to add the adapter type to the config. 

I updated the config with the following in Zigbee2MQTT Edge add-on

```
serial:
  adapter: ezsp
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20221031182937-if00
```

and it failed to start with a new error

```
[17:48:11] INFO: Preparing to start...
[17:48:14] INFO: Socat not enabled
[17:48:27] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-01-26 17:48:53: Logging to console and directory: '/config/zigbee2mqtt/log/2023-01-26.17-48-53' filename: log.txt
Zigbee2MQTT:info  2023-01-26 17:48:54: Starting Zigbee2MQTT version 1.29.2-dev (commit #6ce2d2e)
Zigbee2MQTT:info  2023-01-26 17:48:54: Starting zigbee-herdsman (0.14.88)
Zigbee2MQTT:error 2023-01-26 17:50:05: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-26 17:50:05: Failed to start zigbee
Zigbee2MQTT:error 2023-01-26 17:50:05: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-26 17:50:05: Exiting...
Zigbee2MQTT:error 2023-01-26 17:50:05: Error: Failure send addEndpoint:{"type":"Buffer","data":[22,0,1,2,0,1,4,1,239,190,0,7,20,0,0,3,0,6,0,10,0,25,0,26,0,0,3,0,0,3,0,4,0,5,0,6,0,8,0,32,0,0,3,0,4,2,4,5,4,6,4,0,5,1,11,3,11,4,11,2,7,0,16,1,252,2,252]}
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:516:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```
