### ISSUE TITLE
Zigbee2MQTT won't start on Home Assistant

### ISSUE THREAD

**Issue by Riky-AH** [nurikk/z2m-frontend#1681]
Hi, i'm having trouble starting Zigbee2MQTT on Home Assistant installed on a Virtualbox vm. When i press the start button of ZIgbee2MQTT the cpu usage goes way beyond 100% (sometimes even 1200%), log get stuck at "Zigbee2MQTT:info  2023-02-14 17:45:13: Starting zigbee-herdsman (0.14.89)" or "error: srsp - sys - getextaddr after 6000ms", the ha Zigbee2MQTT interface say "502: Bad Gateway" and after few minutes the addon stops by itself. The issue seems only on Zigbee2MQTT because the coordinator is recognised properly and with Mosquitto i'm able to connect devices (i have tried with some Sonoff temperature and humidity sensors) and get data from them. What am i doing wrong?

**config**

```
 data_path: /config/zigbee2mqtt
 socat:
   enabled: false
   master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
   slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
   options: "-d -d"
   log: false
 mqtt:
   base_topic: zigbee2mqtt
   server: mqtt://172.16.34.113:1883
 serial:
   port: >-
     /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
   adapter: ezsp
 homeassistant: true
 permit_join: false
```

**Zigbee2MQTT addon version**

1.30.1-1

**Platform**

Home Assistant 2023.2.4
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest
