### ISSUE TITLE
[Bug]: Websockets are not accessible behind reverse proxy

### ISSUE THREAD

**Issue by dfuchss** [nurikk/z2m-frontend#2093]
### What happened?

Hi everyone, I want to place the zigbee2mqtt behind a reverse proxy; i.e., traefik in my case.

My docker-compose configuration defines the connection to the frontend
```yaml
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: always
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt-intern.rule=Host(`zigbee2mqtt.my.domain`)"
      - "traefik.http.routers.zigbee2mqtt-intern.entrypoints=websecure"
      - "traefik.http.routers.zigbee2mqtt-intern.tls=true"
      - "traefik.http.routers.zigbee2mqtt-intern.service=zigbee2mqtt"
      - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"
    environment:
      - TZ=Europe/Berlin
    networks:
      - homeassistant
      - web
```

I can also connect to the frontend 
![image](https://github.com/user-attachments/assets/56e080ae-4ad4-43ae-a30a-459604b0f856)

For me, the problem is, that the connection to `/api` (Websocket as far as I can see) fails with response code "302 Found".

![image](https://github.com/user-attachments/assets/9abdb79d-fa42-4202-84b2-9fcc26eb63c8)

Interestingly, the problem occurs on Firefox; on my mobile browser (Safari) the /api request works. 
Does anyone has an idea what the frontend issue might be?

### What browsers are you seeing the problem on?

Firefox

### Did you download state.json.zip?

I will not attach state.json.zip
