### ISSUE TITLE
Custom page title

### ISSUE THREAD

**Issue by uboness** [nurikk/z2m-frontend#2117]
**Is your feature request related to a problem? Please describe.**
Right now the page title is fixed to "Zigbee2MQTT". When you have multiple instance of z2m and you have multiple tab open to these instances, it's hard to distinguish between them (which tab points to which instance).

**Describe the solution you'd like**
The page title should be customizable in the z2m configuration file under the `frontend` key. E.g.:

```yaml
frontend: 
  port: 8080
  title: "Z2M - Instance 1"
```
