### ISSUE TITLE
[feature request] Per-device setting of  availability timeout 

### ISSUE THREAD

**Issue by calebns** [nurikk/z2m-frontend#2227]
**Is your feature request related to a problem? Please describe.**
I'd like to have a possibility of changing global availability timeout for some devices while still retaining the global one for others.
A typical case for this feature is having temperature sensors and door sensors in the same zigbee network. Temp sensors report state every couple of minutes (up to an hour) but door sensors do it even once a day if not being triggered. That means there is no single setting which could work for both of them if a quick detection of malfunctioning sensor is required.
According to Zigbee2MQTT doc it should be possible by setting just one line in configuration.yaml

```
devices:
    '0x87654321':
        friendly_name: 'my_switch'
        # Change availability timeout to 3 minutes for this device only
        availability:
            timeout: 3
```

**Describe the solution you'd like**
It would be best to have another field in Devices->Setting where I could choose the specific timeout.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
