### ISSUE TITLE
Error loading devices with docker compose

### ISSUE THREAD

**Issue by onlymejosh** [nurikk/z2m-frontend#237]
hey, I am running into issues getting the frontend for z2m loading with `docker-compose` similar to the issues listed here https://github.com/Koenkk/zigbee2mqtt/issues/4266#issuecomment-752680322

here is my docker compose service:
```
zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    image: koenkk/zigbee2mqtt:1.16.2
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    privileged: true
    environment:
      - TZ=Europe/London
    network_mode: host
    ports:
      - 8080:8080
```

I get the error
```Loading devices takes too long time. Consider reading documentation```
When visiting http://10.27.1.114:8080/

I dont see any errors in the logs both console and zigbee2mqtt
