### ISSUE TITLE
No config data from zigbee2mqtt

### ISSUE THREAD

**Issue by VincentSC** [nurikk/z2m-frontend#488]
It worked for months. I rebooted and now got a non-working frontend, while z2m just works. Updated to latest z2m-dev, but that didn't help. The reason for rebooting was a misbehaving device, which I force-removed and tried to connect again.

settings/raw gives:
```
{
    "configSchema": {
        "properties": {},
        "required": []
    },
    "config": {
        "advanced": {}
    }
}
```
As you can imagine, nothing works if this does not work. So it gives for example the something-went-wrong error "Loading devices takes too long time.Consider reading documentation", the network-map loads forever and there are no logs,

This is my zigbee2mqtt config:
```
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
serial:
  port: /dev/ttyZZH
frontend:
  port: 8080
  host: 0.0.0.0
advanced:
  log_level: debug
  pan_id: 6755
  rtscts: false
  network_key:
    - ...
  last_seen: ISO_8601_local
  elapsed: true
devices:
  ...
```

Not sure how to debug this, or where to start. It could be that the problem is with z2m, as it does not provide the data.
